### ISSUE TITLE
CDK の雛形を作りたい

### ISSUE THREAD

**Issue by matsuihidetoshi** [jaws-ug/jpk2024-broadcast-backend#1]
# 概要
バックエンドはどの環境にデプロイするかわからないので、 IaC 管理としたいです。
そして、松井の好みもだいぶ入っちゃってますが、 AWS 公式かつコミュニティで盛り上がっているツールということもあり、 CDK でやれればなと思っています。
ただ、手動でマネコンポチポチでやっちゃった方が早いとか、良いとかもあると思うので、そういう手動手順についてもできるだけこのリポジトリのどこかしらの階層の README なり Wiki 形で残しておけると好ましいです。

# tasks
- [x] cdk init する
- [x] 機能ごとに分割してデプロイできるように複数 Stack でデプロイできるようにする
- [x] 環境変数や context はできるだけ使わずに設定ファイルを作ってハードコーディングする
- [x] クレデンシャル系は持たせないように努力するが、どうしても必要な場合は SSM Parameter Store / SecretManager などを使用する

**Comment by soda1p2** [comment]
@matsuihidetoshi 
まずはGithubレポジトリにREADMEを追記しています。

以降の作業はfeature/issue1ブランチでやります！
